using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using SourceCode.SmartObjects.Client;
using SourceCode.Hosting.Client.BaseAPI;
using System.Data.Common;
using System.IO;
using System.Xml.XPath;
using System.Configuration;

namespace eInvoiceK2SAPBroker
{

    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //
    //     .Net class implementation for SmartObject eInvoiceSAP.
    //     Changes to this file may cause incorrect behavior
    // </auto-generated>
    //------------------------------------------------------------------------------

    public class eInvoiceSAP : eInvoiceSAP_properties
    {
        #region Fields (4)

        private readonly string _connectionString;
        private SmartObject _smartObject;
        //private const string cHOST = "localhost";
        //private const string cHOST = "ROK2DEV01";
        private string cHOST = ConfigurationManager.AppSettings["K2ServerName"];
        //private const uint cPORT = 5555;
        private uint cPORT = Convert.ToUInt32(ConfigurationManager.AppSettings["K2ManagementServerPort"]);

        #endregion Fields

        #region Constructors (2)

        public eInvoiceSAP(string connectionString)
        {
            _connectionString = connectionString;
            this.GetSmartObject();
        }
        public eInvoiceSAP()
        {
            SCConnectionStringBuilder hostServerConnectionString = new SCConnectionStringBuilder();
            hostServerConnectionString.Host = cHOST;
            hostServerConnectionString.Port = cPORT;
            hostServerConnectionString.IsPrimaryLogin = true;
            hostServerConnectionString.Integrated = true;
            _connectionString = hostServerConnectionString.ConnectionString;
            this.GetSmartObject();
        }

        #endregion Constructors

        #region Methods (8)

        // Public Methods (2) 

        public DataTable eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2(string p_Ac_Doc_No, string p_Status_Only)
        {
            // Verify required properties

            if (p_Ac_Doc_No == null)
            {
                throw new NullReferenceException("Value required for property [p_Ac_Doc_No]");
            }
            if (p_Status_Only == null)
            {
                throw new NullReferenceException("Value required for property [p_Status_Only]");
            }

            // Set method to execute
            _smartObject.MethodToExecute = "eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2";

            // Assign Input properties
            if (p_Ac_Doc_No != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["p_Ac_Doc_No"], p_Ac_Doc_No);
            }
            if (p_Status_Only != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["p_Status_Only"], p_Status_Only);
            }
            if (Et_Invitems_Gl_Account != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Gl_Account"], Et_Invitems_Gl_Account);
            }
            if (Et_Invitems_Po_Number != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Po_Number"], Et_Invitems_Po_Number);
            }
            if (Et_Invitems_Po_Item != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Po_Item"], Et_Invitems_Po_Item);
            }
            if (Et_Invitems_Wbs_Element != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Wbs_Element"], Et_Invitems_Wbs_Element);
            }
            if (Et_Invitems_Costcenter != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Costcenter"], Et_Invitems_Costcenter);
            }
            if (Et_Invitems_Fund != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Fund"], Et_Invitems_Fund);
            }
            if (Et_Invitems_Func_Area != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Func_Area"], Et_Invitems_Func_Area);
            }
            if (Et_Invitems_Grant_Nbr != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Grant_Nbr"], Et_Invitems_Grant_Nbr);
            }
            if (Et_Invitems_Order_Number != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Order_Number"], Et_Invitems_Order_Number);
            }
            if (Et_Invitems_Amount != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Amount"], Et_Invitems_Amount);
            }
            if (Et_Invitems_Db_Cr_Ind != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Db_Cr_Ind"], Et_Invitems_Db_Cr_Ind);
            }

            try
            {
                SmartObjectClientServer soServer = CreateConnection();

                // Execute SmartObject
                using (soServer.Connection)
                {
                    return soServer.ExecuteListDataTable(_smartObject);
                }

            }
            catch (Exception ex)
            {
                throw DisplayError(ex);
            }
            finally
            {
                ClearProperties();
            }
        }

        public DbDataReader eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2_Reader(string p_Ac_Doc_No, string p_Status_Only)
        {
            // Verify required properties

            if (p_Ac_Doc_No == null)
            {
                throw new NullReferenceException("Value required for property [p_Ac_Doc_No]");
            }
            if (p_Status_Only == null)
            {
                throw new NullReferenceException("Value required for property [p_Status_Only]");
            }

            // Set method to execute
            _smartObject.MethodToExecute = "eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2";

            // Assign Input properties
            if (p_Ac_Doc_No != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["p_Ac_Doc_No"], p_Ac_Doc_No);
            }
            if (p_Status_Only != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["p_Status_Only"], p_Status_Only);
            }
            if (Et_Invitems_Gl_Account != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Gl_Account"], Et_Invitems_Gl_Account);
            }
            if (Et_Invitems_Po_Number != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Po_Number"], Et_Invitems_Po_Number);
            }
            if (Et_Invitems_Po_Item != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Po_Item"], Et_Invitems_Po_Item);
            }
            if (Et_Invitems_Wbs_Element != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Wbs_Element"], Et_Invitems_Wbs_Element);
            }
            if (Et_Invitems_Costcenter != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Costcenter"], Et_Invitems_Costcenter);
            }
            if (Et_Invitems_Fund != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Fund"], Et_Invitems_Fund);
            }
            if (Et_Invitems_Func_Area != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Func_Area"], Et_Invitems_Func_Area);
            }
            if (Et_Invitems_Grant_Nbr != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Grant_Nbr"], Et_Invitems_Grant_Nbr);
            }
            if (Et_Invitems_Order_Number != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Order_Number"], Et_Invitems_Order_Number);
            }
            if (Et_Invitems_Amount != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Amount"], Et_Invitems_Amount);
            }
            if (Et_Invitems_Db_Cr_Ind != null)
            {
                SetPropertyValue(_smartObject.ListMethods["eInvoiceLoadDocNoFromSAP_Bapi_Z_Invoice_To_K2"].InputProperties["Et_Invitems_Db_Cr_Ind"], Et_Invitems_Db_Cr_Ind);
            }

            try
            {
                SmartObjectClientServer soServer = CreateConnection();

                // Execute SmartObject
                using (soServer.Connection)
                {
                    return soServer.ExecuteListReader(_smartObject);
                }

            }
            catch (Exception ex)
            {
                throw DisplayError(ex);
            }
            finally
            {
                ClearProperties();
            }
        }


        // Private Methods (6) 

        private void ClearProperties()
        {
            foreach (SmartProperty property in _smartObject.Properties)
            {
                property.Clear();
                property.ValueBehaviour = ValueBehaviour.None;
            }
        }

        private SmartObjectClientServer CreateConnection()
        {
            SmartObjectClientServer soServer = new SmartObjectClientServer();
            soServer.CreateConnection();
            soServer.Connection.Open(_connectionString);
            return soServer;
        }

        private Exception DisplayError(Exception ex)
        {
            if (ex is SmartObjectException)
            {
                return DisplayError(ex as SmartObjectException);
            }
            else
            {
                return ex;
            }
        }

        private Exception DisplayError(SmartObjectException smartObjectException)
        {
            StringBuilder errorMessage = new StringBuilder();
            foreach (SmartObjectExceptionData smartobjectExceptionData in smartObjectException.BrokerData)
            {
                string message = smartobjectExceptionData.Message;
                string service = smartobjectExceptionData.ServiceName;
                string serviceGuid = smartobjectExceptionData.ServiceGuid;
                string severity = smartobjectExceptionData.Severity.ToString();
                string innermessage = smartobjectExceptionData.InnerExceptionMessage;
                errorMessage.AppendLine(message);
                errorMessage.AppendLine();
                errorMessage.AppendLine("Service: " + service);
                errorMessage.AppendLine("Service Guid: " + serviceGuid);
                errorMessage.AppendLine("Severity: " + severity);
                if (!string.IsNullOrEmpty(innermessage))
                {
                    errorMessage.AppendLine("InnerException Message: " + innermessage);
                }
            }
            return new Exception(errorMessage.ToString());
        }

        private void GetSmartObject()
        {
            SmartObjectClientServer clientServer = CreateConnection();
            using (clientServer.Connection)
            {
                _smartObject = clientServer.GetSmartObject("eInvoiceSAP");
            }
        }

        private static void SetPropertyValue(SmartProperty smartProperty, object value)
        {
            if (value == null)
            {
                smartProperty.ValueBehaviour = ValueBehaviour.Unchanged;
                smartProperty.Value = null;
            }
            else if (value == DBNull.Value)
            {
                smartProperty.ValueBehaviour = ValueBehaviour.Clear;
                smartProperty.Value = null;
            }
            else if (value.ToString() == string.Empty)
            {
                smartProperty.ValueBehaviour = ValueBehaviour.Empty;
                smartProperty.Value = string.Empty;
            }
            else
            {
                smartProperty.ValueBehaviour = ValueBehaviour.None;
                smartProperty.Value = value.ToString();
            }
        }

        #endregion Methods
    }

    public class eInvoiceSAP_properties
    {
        #region Fields (24)

        private string _Vendor_Data_Vendor_No;
        private string _Vendor_Data_Name;
        private string _Vendor_Data_Name_2;
        private string _Vendor_Data_Item_Text;
        private string _Vendor_Data_Po_Number;
        private string _Vendor_Data_Ac_Doc_No;
        private DateTime? _Vendor_Data_Due_Date;
        private double? _Vendor_Data_Inv_Amount;
        private string _Vendor_Data_Entered_By;
        private string _Vendor_Data_Doc_Status;
        private string _Vendor_Data_Status_Text;
        private string _Vendor_Data_Pmnt_Block;
        private string _Vendor_Data_Pmnt_Blktx;

        private string _Et_Invitems_Gl_Account;
        private string _Et_Invitems_Po_Number;
        private double? _Et_Invitems_Po_Item;
        private string _Et_Invitems_Wbs_Element;
        private string _Et_Invitems_Costcenter;
        private string _Et_Invitems_Fund;
        private string _Et_Invitems_Func_Area;
        private string _Et_Invitems_Grant_Nbr;
        private string _Et_Invitems_Order_Number;
        private double? _Et_Invitems_Amount;
        private string _Et_Invitems_Db_Cr_Ind;

        #endregion Fields

        #region Constructors (1)

        protected eInvoiceSAP_properties()
        {
        }

        #endregion Constructors

        #region Properties (24)

        public string Vendor_Data_Vendor_No
        {
            get
            {
                return _Vendor_Data_Vendor_No;
            }
            set
            {
                _Vendor_Data_Vendor_No = value;
            }
        }

        public string Vendor_Data_Name
        {
            get
            {
                return _Vendor_Data_Name;
            }
            set
            {
                _Vendor_Data_Name = value;
            }
        }

        public string Vendor_Data_Name_2
        {
            get
            {
                return _Vendor_Data_Name_2;
            }
            set
            {
                _Vendor_Data_Name_2 = value;
            }
        }

        public string Vendor_Data_Item_Text
        {
            get
            {
                return _Vendor_Data_Item_Text;
            }
            set
            {
                _Vendor_Data_Item_Text = value;
            }
        }

        public string Vendor_Data_Po_Number
        {
            get
            {
                return _Vendor_Data_Po_Number;
            }
            set
            {
                _Vendor_Data_Po_Number = value;
            }
        }

        public string Vendor_Data_Ac_Doc_No
        {
            get
            {
                return _Vendor_Data_Ac_Doc_No;
            }
            set
            {
                _Vendor_Data_Ac_Doc_No = value;
            }
        }

        public DateTime? Vendor_Data_Due_Date
        {
            get
            {
                return _Vendor_Data_Due_Date;
            }
            set
            {
                _Vendor_Data_Due_Date = value;
            }
        }

        public double? Vendor_Data_Inv_Amount
        {
            get
            {
                return _Vendor_Data_Inv_Amount;
            }
            set
            {
                _Vendor_Data_Inv_Amount = value;
            }
        }

        public string Vendor_Data_Entered_By
        {
            get
            {
                return _Vendor_Data_Entered_By;
            }
            set
            {
                _Vendor_Data_Entered_By = value;
            }
        }

        public string Vendor_Data_Doc_Status
        {
            get
            {
                return _Vendor_Data_Doc_Status;
            }
            set
            {
                _Vendor_Data_Doc_Status = value;
            }
        }

        public string Vendor_Data_Status_Text
        {
            get
            {
                return _Vendor_Data_Status_Text;
            }
            set
            {
                _Vendor_Data_Status_Text = value;
            }
        }

        public string Vendor_Data_Pmnt_Block
        {
            get
            {
                return _Vendor_Data_Pmnt_Block;
            }
            set
            {
                _Vendor_Data_Pmnt_Block = value;
            }
        }

        public string Vendor_Data_Pmnt_Blktx
        {
            get
            {
                return _Vendor_Data_Pmnt_Blktx;
            }
            set
            {
                _Vendor_Data_Pmnt_Blktx = value;
            }
        }

        public string Et_Invitems_Gl_Account
        {
            get
            {
                return _Et_Invitems_Gl_Account;
            }
            set
            {
                _Et_Invitems_Gl_Account = value;
            }
        }

        public string Et_Invitems_Po_Number
        {
            get
            {
                return _Et_Invitems_Po_Number;
            }
            set
            {
                _Et_Invitems_Po_Number = value;
            }
        }

        public double? Et_Invitems_Po_Item
        {
            get
            {
                return _Et_Invitems_Po_Item;
            }
            set
            {
                _Et_Invitems_Po_Item = value;
            }
        }

        public string Et_Invitems_Wbs_Element
        {
            get
            {
                return _Et_Invitems_Wbs_Element;
            }
            set
            {
                _Et_Invitems_Wbs_Element = value;
            }
        }

        public string Et_Invitems_Costcenter
        {
            get
            {
                return _Et_Invitems_Costcenter;
            }
            set
            {
                _Et_Invitems_Costcenter = value;
            }
        }

        public string Et_Invitems_Fund
        {
            get
            {
                return _Et_Invitems_Fund;
            }
            set
            {
                _Et_Invitems_Fund = value;
            }
        }

        public string Et_Invitems_Func_Area
        {
            get
            {
                return _Et_Invitems_Func_Area;
            }
            set
            {
                _Et_Invitems_Func_Area = value;
            }
        }

        public string Et_Invitems_Grant_Nbr
        {
            get
            {
                return _Et_Invitems_Grant_Nbr;
            }
            set
            {
                _Et_Invitems_Grant_Nbr = value;
            }
        }

        public string Et_Invitems_Order_Number
        {
            get
            {
                return _Et_Invitems_Order_Number;
            }
            set
            {
                _Et_Invitems_Order_Number = value;
            }
        }

        public double? Et_Invitems_Amount
        {
            get
            {
                return _Et_Invitems_Amount;
            }
            set
            {
                _Et_Invitems_Amount = value;
            }
        }

        public string Et_Invitems_Db_Cr_Ind
        {
            get
            {
                return _Et_Invitems_Db_Cr_Ind;
            }
            set
            {
                _Et_Invitems_Db_Cr_Ind = value;
            }
        }


        #endregion Properties

        #region Methods (25)

        // Protected Methods (25) 
        protected eInvoiceSAP_properties GetPropertiesObject()
        {
            return new eInvoiceSAP_properties();
        }

        protected static string SetProperty_Vendor_Data_Vendor_No(string Vendor_Data_Vendor_No)
        {
            if (Vendor_Data_Vendor_No == null)
            {
                return null;
            }


            if (Vendor_Data_Vendor_No == string.Empty)
            {
                return null;
            }

            return Vendor_Data_Vendor_No;
        }

        protected static string SetProperty_Vendor_Data_Name(string Vendor_Data_Name)
        {
            if (Vendor_Data_Name == null)
            {
                return null;
            }


            if (Vendor_Data_Name == string.Empty)
            {
                return null;
            }

            return Vendor_Data_Name;
        }

        protected static string SetProperty_Vendor_Data_Name_2(string Vendor_Data_Name_2)
        {
            if (Vendor_Data_Name_2 == null)
            {
                return null;
            }


            if (Vendor_Data_Name_2 == string.Empty)
            {
                return null;
            }

            return Vendor_Data_Name_2;
        }

        protected static string SetProperty_Vendor_Data_Item_Text(string Vendor_Data_Item_Text)
        {
            if (Vendor_Data_Item_Text == null)
            {
                return null;
            }


            if (Vendor_Data_Item_Text == string.Empty)
            {
                return null;
            }

            return Vendor_Data_Item_Text;
        }

        protected static string SetProperty_Vendor_Data_Po_Number(string Vendor_Data_Po_Number)
        {
            if (Vendor_Data_Po_Number == null)
            {
                return null;
            }


            if (Vendor_Data_Po_Number == string.Empty)
            {
                return null;
            }

            return Vendor_Data_Po_Number;
        }

        protected static string SetProperty_Vendor_Data_Ac_Doc_No(string Vendor_Data_Ac_Doc_No)
        {
            if (Vendor_Data_Ac_Doc_No == null)
            {
                return null;
            }


            if (Vendor_Data_Ac_Doc_No == string.Empty)
            {
                return null;
            }

            return Vendor_Data_Ac_Doc_No;
        }

        protected static DateTime? SetProperty_Vendor_Data_Due_Date(string Vendor_Data_Due_Date)
        {
            if (Vendor_Data_Due_Date == null)
            {
                return null;
            }


            if (Vendor_Data_Due_Date == string.Empty)
            {
                return null;
            }

            return Convert.ToDateTime(Vendor_Data_Due_Date);
        }

        protected static double? SetProperty_Vendor_Data_Inv_Amount(string Vendor_Data_Inv_Amount)
        {
            if (Vendor_Data_Inv_Amount == null)
            {
                return null;
            }


            if (Vendor_Data_Inv_Amount == string.Empty)
            {
                return null;
            }

            return double.Parse(Vendor_Data_Inv_Amount);
        }

        protected static string SetProperty_Vendor_Data_Entered_By(string Vendor_Data_Entered_By)
        {
            if (Vendor_Data_Entered_By == null)
            {
                return null;
            }


            if (Vendor_Data_Entered_By == string.Empty)
            {
                return null;
            }

            return Vendor_Data_Entered_By;
        }

        protected static string SetProperty_Vendor_Data_Doc_Status(string Vendor_Data_Doc_Status)
        {
            if (Vendor_Data_Doc_Status == null)
            {
                return null;
            }


            if (Vendor_Data_Doc_Status == string.Empty)
            {
                return null;
            }

            return Vendor_Data_Doc_Status;
        }

        protected static string SetProperty_Vendor_Data_Status_Text(string Vendor_Data_Status_Text)
        {
            if (Vendor_Data_Status_Text == null)
            {
                return null;
            }


            if (Vendor_Data_Status_Text == string.Empty)
            {
                return null;
            }

            return Vendor_Data_Status_Text;
        }

        protected static string SetProperty_Vendor_Data_Pmnt_Block(string Vendor_Data_Pmnt_Block)
        {
            if (Vendor_Data_Pmnt_Block == null)
            {
                return null;
            }


            if (Vendor_Data_Pmnt_Block == string.Empty)
            {
                return null;
            }

            return Vendor_Data_Pmnt_Block;
        }

        protected static string SetProperty_Vendor_Data_Pmnt_Blktx(string Vendor_Data_Pmnt_Blktx)
        {
            if (Vendor_Data_Pmnt_Blktx == null)
            {
                return null;
            }


            if (Vendor_Data_Pmnt_Blktx == string.Empty)
            {
                return null;
            }

            return Vendor_Data_Pmnt_Blktx;
        }

        protected static string SetProperty_Et_Invitems_Gl_Account(string Et_Invitems_Gl_Account)
        {
            if (Et_Invitems_Gl_Account == null)
            {
                return null;
            }


            if (Et_Invitems_Gl_Account == string.Empty)
            {
                return null;
            }

            return Et_Invitems_Gl_Account;
        }

        protected static string SetProperty_Et_Invitems_Po_Number(string Et_Invitems_Po_Number)
        {
            if (Et_Invitems_Po_Number == null)
            {
                return null;
            }


            if (Et_Invitems_Po_Number == string.Empty)
            {
                return null;
            }

            return Et_Invitems_Po_Number;
        }

        protected static double? SetProperty_Et_Invitems_Po_Item(string Et_Invitems_Po_Item)
        {
            if (Et_Invitems_Po_Item == null)
            {
                return null;
            }


            if (Et_Invitems_Po_Item == string.Empty)
            {
                return null;
            }

            return double.Parse(Et_Invitems_Po_Item);
        }

        protected static string SetProperty_Et_Invitems_Wbs_Element(string Et_Invitems_Wbs_Element)
        {
            if (Et_Invitems_Wbs_Element == null)
            {
                return null;
            }


            if (Et_Invitems_Wbs_Element == string.Empty)
            {
                return null;
            }

            return Et_Invitems_Wbs_Element;
        }

        protected static string SetProperty_Et_Invitems_Costcenter(string Et_Invitems_Costcenter)
        {
            if (Et_Invitems_Costcenter == null)
            {
                return null;
            }


            if (Et_Invitems_Costcenter == string.Empty)
            {
                return null;
            }

            return Et_Invitems_Costcenter;
        }

        protected static string SetProperty_Et_Invitems_Fund(string Et_Invitems_Fund)
        {
            if (Et_Invitems_Fund == null)
            {
                return null;
            }


            if (Et_Invitems_Fund == string.Empty)
            {
                return null;
            }

            return Et_Invitems_Fund;
        }

        protected static string SetProperty_Et_Invitems_Func_Area(string Et_Invitems_Func_Area)
        {
            if (Et_Invitems_Func_Area == null)
            {
                return null;
            }


            if (Et_Invitems_Func_Area == string.Empty)
            {
                return null;
            }

            return Et_Invitems_Func_Area;
        }

        protected static string SetProperty_Et_Invitems_Grant_Nbr(string Et_Invitems_Grant_Nbr)
        {
            if (Et_Invitems_Grant_Nbr == null)
            {
                return null;
            }


            if (Et_Invitems_Grant_Nbr == string.Empty)
            {
                return null;
            }

            return Et_Invitems_Grant_Nbr;
        }

        protected static string SetProperty_Et_Invitems_Order_Number(string Et_Invitems_Order_Number)
        {
            if (Et_Invitems_Order_Number == null)
            {
                return null;
            }


            if (Et_Invitems_Order_Number == string.Empty)
            {
                return null;
            }

            return Et_Invitems_Order_Number;
        }

        protected static double? SetProperty_Et_Invitems_Amount(string Et_Invitems_Amount)
        {
            if (Et_Invitems_Amount == null)
            {
                return null;
            }


            if (Et_Invitems_Amount == string.Empty)
            {
                return null;
            }

            return double.Parse(Et_Invitems_Amount);
        }

        protected static string SetProperty_Et_Invitems_Db_Cr_Ind(string Et_Invitems_Db_Cr_Ind)
        {
            if (Et_Invitems_Db_Cr_Ind == null)
            {
                return null;
            }


            if (Et_Invitems_Db_Cr_Ind == string.Empty)
            {
                return null;
            }

            return Et_Invitems_Db_Cr_Ind;
        }


        #endregion Methods

    }

    #region Object Classes

    //public abstract class NamedObject
    //{

    //    #region Fields (3)

    //    private string _name;
    //    private string _value;
    //    protected const string SCNULL = "scnull";

    //    #endregion Fields

    //    #region Constructors (2)

    //    public NamedObject(string name, string value)
    //    {
    //        _name = name;
    //        _value = value;
    //    }

    //    public NamedObject(string inputValue)
    //    {
    //        this.FromValue(inputValue);
    //    }

    //    #endregion Constructors

    //    #region Properties (2)

    //    public string Name
    //    {
    //        get
    //        {
    //            return _name;
    //        }
    //        set
    //        {
    //            _name = value;
    //        }
    //    }

    //    public string Value
    //    {
    //        get
    //        {
    //            return _value;
    //        }
    //        set
    //        {
    //            _value = value;
    //        }
    //    }

    //    #endregion Properties

    //    #region Methods (3)

    //    // Public Methods (3) 

    //    public abstract void FromValue(string inputValue);

    //    public override string ToString()
    //    {
    //        return ToValue();
    //    }

    //    public abstract string ToValue();

    //    #endregion Methods

    //}

    //public class ImageObject : NamedObject
    //{

    //    #region Constructors (2)

    //    public ImageObject(string name, string value)
    //        : base(name, value)
    //    {
    //    }

    //    public ImageObject(string inputValue)
    //        : base(inputValue)
    //    {
    //    }

    //    #endregion Constructors

    //    #region Methods (2)

    //    // Public Methods (2) 
    //    public override void FromValue(string inputValue)
    //    {
    //        if (!string.IsNullOrEmpty(inputValue))
    //        {
    //            using (StringReader reader = new StringReader(inputValue))
    //            {
    //                XPathDocument xDoc = new XPathDocument(reader);
    //                XPathNavigator xNav = xDoc.CreateNavigator();
    //                string imageNameValue = xNav.SelectSingleNode("image/name").InnerXml;
    //                string contentValue = xNav.SelectSingleNode("image/content").InnerXml;
    //                if (imageNameValue == SCNULL)
    //                    this.Name = string.Empty;
    //                else
    //                    this.Name = imageNameValue;
    //                if (contentValue == SCNULL)
    //                    this.Value = string.Empty;
    //                else
    //                    this.Value = contentValue;
    //            }
    //        }
    //        else
    //        {
    //            this.Value = string.Empty;
    //            this.Name = string.Empty;
    //        }
    //    }

    //    public override string ToValue()
    //    {
    //        StringBuilder sb = new StringBuilder();
    //        sb.Append("<image>");
    //        if (this.Name == null)
    //        {
    //            sb.Append("<name/>");
    //        }
    //        else
    //        {
    //            sb.Append("<name>");
    //            sb.Append(this.Name);
    //            sb.Append("</name>");
    //        }
    //        if (this.Value == null)
    //        {
    //            sb.Append("<content/>");
    //        }
    //        else
    //        {
    //            sb.Append("<content>");
    //            sb.Append(this.Value);
    //            sb.Append("</content>");
    //        }
    //        sb.Append("</image>");
    //        return sb.ToString();
    //    }

    //    #endregion Methods

    //}

    //public class FileObject : NamedObject
    //{

    //    #region Constructors (2)

    //    public FileObject(string name, string value)
    //        : base(name, value)
    //    {
    //    }

    //    public FileObject(string inputValue)
    //        : base(inputValue)
    //    {
    //    }

    //    #endregion Constructors

    //    #region Methods (2)

    //    // Public Methods (2) 
    //    public override void FromValue(string inputValue)
    //    {
    //        if (!string.IsNullOrEmpty(inputValue))
    //        {
    //            using (StringReader reader = new StringReader(inputValue))
    //            {
    //                XPathDocument xDoc = new XPathDocument(reader);
    //                XPathNavigator xNav = xDoc.CreateNavigator();
    //                string fileNameValue = xNav.SelectSingleNode("file/name").InnerXml;
    //                string contentValue = xNav.SelectSingleNode("file/content").InnerXml;
    //                if (fileNameValue == SCNULL)
    //                    this.Name = string.Empty;
    //                else
    //                    this.Name = fileNameValue;
    //                if (contentValue == SCNULL)
    //                    this.Value = string.Empty;
    //                else
    //                    this.Value = contentValue;
    //            }
    //        }
    //        else
    //        {
    //            this.Value = string.Empty;
    //            this.Name = string.Empty;
    //        }
    //    }

    //    public override string ToValue()
    //    {
    //        StringBuilder sb = new StringBuilder();
    //        sb.Append("<file>");
    //        if (this.Name == null)
    //        {
    //            sb.Append("<name/>");
    //        }
    //        else
    //        {
    //            sb.Append("<name>");
    //            sb.Append(this.Name);
    //            sb.Append("</name>");
    //        }
    //        if (this.Value == null)
    //        {
    //            sb.Append("<content/>");
    //        }
    //        else
    //        {
    //            sb.Append("<content>");
    //            sb.Append(this.Value);
    //            sb.Append("</content>");
    //        }
    //        sb.Append("</file>");
    //        return sb.ToString();
    //    }

    //    #endregion Methods

    //}

    //public class HyperLinkObject : NamedObject
    //{

    //    #region Constructors (2)

    //    public HyperLinkObject(string name, string value)
    //        : base(name, value)
    //    {
    //    }

    //    public HyperLinkObject(string inputValue)
    //        : base(inputValue)
    //    {
    //    }

    //    #endregion Constructors

    //    #region Methods (2)

    //    // Public Methods (2) 

    //    public override void FromValue(string inputValue)
    //    {
    //        if (!string.IsNullOrEmpty(inputValue))
    //        {
    //            using (StringReader reader = new StringReader(inputValue))
    //            {
    //                XPathDocument xDoc = new XPathDocument(reader);
    //                XPathNavigator xNav = xDoc.CreateNavigator();
    //                string hyperLinkNameValue = xNav.SelectSingleNode("hyperlink/display").InnerXml;
    //                string contentValue = xNav.SelectSingleNode("hyperlink/link").InnerXml;
    //                if (hyperLinkNameValue == SCNULL)
    //                    this.Name = string.Empty;
    //                else
    //                    this.Name = hyperLinkNameValue;
    //                if (contentValue == SCNULL)
    //                    this.Value = string.Empty;
    //                else
    //                    this.Value = contentValue;
    //            }
    //        }
    //        else
    //        {
    //            this.Value = string.Empty;
    //            this.Name = string.Empty;
    //        }
    //    }

    //    public override string ToValue()
    //    {
    //        StringBuilder sb = new StringBuilder();
    //        sb.Append("<hyperlink>");
    //        if (this.Name == null)
    //        {
    //            sb.Append("<link/>");
    //        }
    //        else
    //        {
    //            sb.Append("<link>");
    //            sb.Append(this.Name);
    //            sb.Append("</link>");
    //        }
    //        if (this.Value == null)
    //        {
    //            sb.Append("<display/>");
    //        }
    //        else
    //        {
    //            sb.Append("<display>");
    //            sb.Append(this.Value);
    //            sb.Append("</display>");
    //        }
    //        sb.Append("</hyperlink>");
    //        return sb.ToString();
    //    }

    //    #endregion Methods

    //}

    #endregion
}


